CREATE TABLE Category (
  CategoryID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE PaymentType (
  PaymentTypeID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  Type VARCHAR(50) NOT NULL
);

CREATE TABLE Location (
  Zipcode INT NOT NULL PRIMARY KEY,
  Address VARCHAR(255) NOT NULL,
);

CREATE TABLE MenuItem (
  MenuItemID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  CategoryID INT,
  Name VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE
);

CREATE TABLE Customer (
  CustomerID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255),
  Zipcode INT,
  FOREIGN KEY (Zipcode) REFERENCES Location(Zipcode) ON DELETE SET NULL
);

CREATE TABLE Payment (
  PaymentID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  PaymentTypeID INT,
  Amount DECIMAL(10,2) NOT NULL,
  PaymentDate DATETIME NOT NULL,
  FOREIGN KEY (PaymentTypeID) REFERENCES PAYMENTTYPE(PaymentTypeID) ON DELETE SET NULL
);

CREATE TABLE Orders (
  OrderID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  CustomerID INT,
  OrderDate DATETIME NOT NULL,
  PaymentID INT,
  RestaurantID INT,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
  FOREIGN KEY (PaymentID) REFERENCES Payment(PaymentID) ON DELETE SET NULL,
  FOREIGN KEY (RestaurantID) REFERENCES RestaurantBranch(RestaurantID) ON DELETE CASCADE
);

CREATE TABLE Ticket (
  TicketID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  OrderID INT,
  MenuItemID INT,
  Quantity INT NOT NULL,
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
  FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID) ON DELETE CASCADE
);
CREATE TABLE EmployeeInfo (
  EmployeeID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Position VARCHAR(255) NOT NULL,
  RestaurantID INT,
  FOREIGN KEY (RestaurantID) REFERENCES RestaurantBranch(RestaurantID) ON DELETE SET NULL
);

CREATE TABLE RestaurantBranch (
   RestaurantID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
   BranchLocation VARCHAR(255) NOT NULL
);